#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LoginSystem.Resource", IsApplication=true)]

namespace LoginSystem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int HomeScreenButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mail = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Profiel = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int RefreshButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int soundimages = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int stopimagess = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int Afbeelding = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int BtnLogIn = 2131296265;
			
			// aapt resource value: 0x7f090017
			public const int Listview = 2131296279;
			
			// aapt resource value: 0x7f090000
			public const int ListviewAfspraken = 2131296256;
			
			// aapt resource value: 0x7f090033
			public const int ListviewMED = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int Medicijn_Toe = 2131296308;
			
			// aapt resource value: 0x7f090001
			public const int afspraken = 2131296257;
			
			// aapt resource value: 0x7f090032
			public const int bewerk = 2131296306;
			
			// aapt resource value: 0x7f090030
			public const int bloedgroep = 2131296304;
			
			// aapt resource value: 0x7f090006
			public const int btnDialogAfspraken = 2131296262;
			
			// aapt resource value: 0x7f090016
			public const int btnDialogEmail = 2131296278;
			
			// aapt resource value: 0x7f09001b
			public const int btnSignIn = 2131296283;
			
			// aapt resource value: 0x7f09001d
			public const int btnSignUp = 2131296285;
			
			// aapt resource value: 0x7f09001f
			public const int button2 = 2131296287;
			
			// aapt resource value: 0x7f09002f
			public const int email = 2131296303;
			
			// aapt resource value: 0x7f090022
			public const int imageButton1 = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int imageButton2 = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int imageButton3 = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int imageButton4 = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int imageButton5 = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int imageButton6 = 2131296295;
			
			// aapt resource value: 0x7f09002e
			public const int naam = 2131296302;
			
			// aapt resource value: 0x7f090031
			public const int potato = 2131296305;
			
			// aapt resource value: 0x7f09002d
			public const int profielpicture = 2131296301;
			
			// aapt resource value: 0x7f09001e
			public const int progressBar1 = 2131296286;
			
			// aapt resource value: 0x7f090029
			public const int radioButton1 = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int radioButton2 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int radioButton3 = 2131296299;
			
			// aapt resource value: 0x7f090028
			public const int radioGroup1 = 2131296296;
			
			// aapt resource value: 0x7f090035
			public const int refresh = 2131296309;
			
			// aapt resource value: 0x7f090018
			public const int supplies = 2131296280;
			
			// aapt resource value: 0x7f09002c
			public const int textView = 2131296300;
			
			// aapt resource value: 0x7f090020
			public const int textView2 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int textView3 = 2131296289;
			
			// aapt resource value: 0x7f090005
			public const int txtBeschrijving = 2131296261;
			
			// aapt resource value: 0x7f09000e
			public const int txtBijsluiter = 2131296270;
			
			// aapt resource value: 0x7f090015
			public const int txtBloedtype = 2131296277;
			
			// aapt resource value: 0x7f09001a
			public const int txtCreateAccount = 2131296282;
			
			// aapt resource value: 0x7f090003
			public const int txtDate = 2131296259;
			
			// aapt resource value: 0x7f09000c
			public const int txtDosering = 2131296268;
			
			// aapt resource value: 0x7f090012
			public const int txtEmail = 2131296274;
			
			// aapt resource value: 0x7f090007
			public const int txtEmail2 = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int txtEmail3 = 2131296258;
			
			// aapt resource value: 0x7f090010
			public const int txtFirstName = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int txtLastName = 2131296273;
			
			// aapt resource value: 0x7f090014
			public const int txtLeeftijd = 2131296276;
			
			// aapt resource value: 0x7f09000a
			public const int txtMedicijn = 2131296266;
			
			// aapt resource value: 0x7f09001c
			public const int txtOr = 2131296284;
			
			// aapt resource value: 0x7f090013
			public const int txtPassword = 2131296275;
			
			// aapt resource value: 0x7f090008
			public const int txtPassword2 = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int txtTijd = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int txtVoorraad = 2131296267;
			
			// aapt resource value: 0x7f09000f
			public const int uploadbutton = 2131296271;
			
			// aapt resource value: 0x7f090019
			public const int user = 2131296281;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int afspraken = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_afspraken = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_login_in = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog_medicijn = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_sign_up = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Home = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Melding = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MeldingErna = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int profielscherm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int voorraadScherm = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int refreshmenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int ialarm = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int radar = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int sunalarm = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int test = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
